from datetime import date

from app.database import SessionLocal
from app.crud import get_payment_period_report

from app.services.payment_report_pdf import (
    generate_payment_report_pdf
)

from app.notifications.email_service import (
    send_email_with_attachment
)

from app.notifications.config import (
    ADMIN_REPORT_EMAIL
)


def test_august_monthly_report():



    start_date = date(
        2026,
        8,
        1
    )

    end_date = date(
        2026,
        8,
        31
    )

    print(
        f"Testing monthly report:"
        f" {start_date} → {end_date}"
    )

    db = SessionLocal()

    try:

        

        report_rows = get_payment_period_report(
            db=db,
            start_date=start_date,
            end_date=end_date
        )

        print(
            f"Report rows found: "
            f"{len(report_rows)}"
        )


        for row in report_rows:

            print(
                f"{row['payment_method_name']} | "
                f"Count: {row['payment_count']} | "
                f"Amount: {row['total_amount']}"
            )

      
        pdf_buffer = generate_payment_report_pdf(
            report_rows=report_rows,
            period="monthly",
            start_date=start_date,
            end_date=end_date
        )

        pdf_bytes = pdf_buffer.getvalue()


        filename = (
            "monthly_payment_report_2026_08.pdf"
        )

        with open(
            filename,
            "wb"
        ) as pdf_file:

            pdf_file.write(
                pdf_bytes
            )

        print(
            f"PDF generated: {filename}"
        )


        send_email_with_attachment(

            to_email=ADMIN_REPORT_EMAIL,

            subject=(
                "Monthly Payment Report - "
                "August 2026"
            ),

            body="""
            <html>
                <body>

                    <h2>
                        Monthly Payment Report
                    </h2>

                    <p>
                        Please find the August
                        2026 payment report attached.
                    </p>

                    <p>
                        <b>Report Period:</b>
                        2026-08-01 to 2026-08-31
                    </p>

                    <p>
                        Generated by Expense
                        Management System.
                    </p>

                </body>
            </html>
            """,

            attachment=pdf_bytes,

            filename=filename
        )

        print(
            "August monthly report email sent successfully."
        )

    finally:

        db.close()


if __name__ == "__main__":

    test_august_monthly_report()