import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, Bell, Check, ChevronRight, CircleDollarSign, FileText, LayoutDashboard, LogOut, Menu, Plus, Receipt, RefreshCw, Search, Settings, Tags, Users, WalletCards, X } from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || ''
const portal = location.pathname.startsWith('/admin-ui') ? 'admin' : location.pathname.startsWith('/vendor-ui') ? 'vendor' : 'employee'
const config = {
  employee: { label: 'Employee', token: 'employee_token', login: '/expenses/login', logout: '/expenses/logout', dashboard: '/dashboard/summary', expense: '/expenses', nav: [['dashboard','Dashboard',LayoutDashboard],['expenses','My expenses',Receipt],['reports','Reports',BarChart3],['wallet','Wallet',WalletCards]] },
  vendor: { label: 'Sub-vendor', token: 'sub_vendor_token', login: '/sub-vendor/login', logout: '/sub-vendor/logout', dashboard: '/sub-vendor/dashboard', expense: '/sub-vendor/expenses', nav: [['dashboard','Dashboard',LayoutDashboard],['expenses','Expenses',Receipt],['employees','Employees',Users],['reports','Payment reports',BarChart3],['wallet','Wallet',WalletCards]] },
  admin: { label: 'Administrator', token: 'admin_token', login: '/admin/login', logout: '/admin/logout', dashboard: '/admin/dashboard', expense: '/admin/expenses', nav: [['dashboard','Overview',LayoutDashboard],['pending','Approval queue',Receipt],['reports','Reports',BarChart3],['wallet','Wallet operations',WalletCards],['categories','Categories',Tags],['vendors','Sub-vendors',Users]] },
}[portal]
const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
async function api(path, options = {}) { const response = await fetch(API + path, { credentials: 'include', ...options, headers: options.body instanceof FormData ? options.headers : { 'Content-Type': 'application/json', ...(options.headers || {}) }, body: options.body && !(options.body instanceof FormData) ? JSON.stringify(options.body) : options.body }); if (!response.ok) { let message = response.statusText; try { const body = await response.json(); message = body.detail || body.message || message } catch {} throw new Error(message) } return response.status === 204 ? null : response.json() }
function App() { const [authenticated, setAuthenticated] = useState(true); const [view, setView] = useState('dashboard'); const [data, setData] = useState(null); const [rows, setRows] = useState([]); const [options, setOptions] = useState(null); const [busy, setBusy] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [modal, setModal] = useState(false); const [mobile, setMobile] = useState(false)
  const load = async () => { setBusy(true); setError(''); try { const [summary, expenses] = await Promise.all([api(config.dashboard), api(config.expense)]); setData(summary); setRows(Array.isArray(expenses) ? expenses : expenses?.expenses || []) } catch (e) { if (e.message.toLowerCase().includes('auth') || e.message.includes('401')) setAuthenticated(false); setError(e.message) } finally { setBusy(false) } }
  useEffect(() => { load() }, [])
  const filtered = useMemo(() => rows.filter(row => JSON.stringify(row).toLowerCase().includes(query.toLowerCase())), [rows, query])
  if (!authenticated) return <Login onLoggedIn={() => { setAuthenticated(true); load() }} />
  const refresh = () => load()
  return <div className="app-shell"><aside className={mobile ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark">L</span><span>Ledger</span></div><div className="workspace"><strong>{config.label} workspace</strong><span>Expense operations</span></div><nav>{config.nav.map(([id, label, Icon]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => { setView(id); setMobile(false) }}><Icon />{label}<ChevronRight className="nav-arrow" /></button>)}</nav><div className="sidebar-footer"><button className="nav-item"><Bell />Notifications</button><button className="nav-item" onClick={async () => { try { await api(config.logout, { method: 'POST' }) } finally { setAuthenticated(false) } }}><LogOut />Sign out</button></div></aside>{mobile && <div className="scrim" onClick={() => setMobile(false)} />}<main><header className="topbar"><button className="mobile-menu" onClick={() => setMobile(true)}><Menu /></button><div><span className="kicker">{config.label.toUpperCase()} / LEDGER</span><h1>{config.nav.find(item => item[0] === view)?.[1] || 'Dashboard'}</h1></div><div className="top-actions"><button className="icon-button" onClick={refresh} aria-label="Refresh"><RefreshCw /></button>{(portal !== 'admin' || view === 'pending') && <button className="primary-button" onClick={async () => { try { setOptions(await api(portal === 'employee' ? '/expenses/options' : '/sub-vendor/options')) } catch {} setModal(true) }}><Plus />New expense</button>}</div></header><div className="page">{error && <div className="alert"><X />{error}<button onClick={refresh}>Retry</button></div>}{view === 'dashboard' && <Dashboard data={data} rows={rows} busy={busy} portal={portal} />}{(view === 'expenses' || view === 'pending') && <Expenses rows={filtered} busy={busy} query={query} setQuery={setQuery} portal={portal} onRefresh={refresh} />}{view === 'reports' && <Reports portal={portal} />}{view === 'wallet' && <Wallet portal={portal} data={data} />}{view === 'employees' && <Employees />}{view === 'categories' && <Categories />}{view === 'vendors' && <Vendors />}</div></main>{modal && <ExpenseModal options={options} onClose={() => setModal(false)} onSaved={() => { setModal(false); refresh() }} />}</div> }
function Login({ onLoggedIn }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [register, setRegister] = useState(false); const [error, setError] = useState(''); const submit = async e => { e.preventDefault(); setError(''); try { await api(register ? '/admin/register' : config.login, { method: 'POST', body: register ? { name, email, password } : portal === 'admin' ? { email_id: email, password } : { email, password } }); if (register) setRegister(false); else onLoggedIn() } catch (err) { setError(err.message) } }; return <div className="auth-shell"><div className="auth-card"><div className="brand auth-brand"><span className="brand-mark">L</span><span>Ledger</span></div><span className="kicker">{config.label.toUpperCase()} ACCESS</span><h1>{register ? 'Create administrator' : `Sign in to your ${config.label.toLowerCase()} workspace`}</h1><p className="muted">Secure session-based access to expense operations.</p>{error && <div className="alert">{error}</div>}<form onSubmit={submit}>{register && <label>Full name<input value={name} onChange={e => setName(e.target.value)} required /></label>}<label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label><button className="primary-button full" type="submit">{register ? 'Create account' : 'Continue'}</button></form>{portal === 'admin' && <button className="text-button" onClick={() => setRegister(!register)}>{register ? 'Back to sign in' : 'Register a new admin'}</button>}</div></div> }
function Dashboard({ data, rows, busy, portal }) { const stats = [['Total spend', money(data?.total_amount || data?.total_spend)], ['Total claims', data?.total_expenses || rows.length], ['Pending', data?.pending || 0], [portal === 'admin' ? 'Approved' : 'Paid', portal === 'admin' ? data?.approved || 0 : data?.paid || 0]]; return <><section className="hero"><div><span className="kicker">{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })}</span><h2>Keep every rupee accountable.</h2><p className="muted">A live view of your expense operations and approvals.</p></div><span className="live"><i />LIVE</span></section><div className="stat-grid">{stats.map(([label, value]) => <article className="stat-card" key={label}><span>{label}</span><strong>{busy ? '—' : value}</strong><small>Current records</small></article>)}</div><div className="two-col"><section className="panel"><div className="panel-heading"><div><span className="kicker">ACTIVITY</span><h3>Recent expenses</h3></div><FileText /></div>{rows.slice(0, 6).map((row, i) => <div className="activity-row" key={row.id || i}><span className="avatar">{String(row.title || row.description || 'E')[0]}</span><div><strong>{row.title || row.description || 'Expense claim'}</strong><small>{row.status || 'Pending'} · {row.expense_date || 'Recently'}</small></div><b>{money(row.amount)}</b></div>)}{!busy && !rows.length && <Empty text="No expenses yet." />}</section><section className="panel note-panel"><span className="kicker">OPERATIONS NOTE</span><h3>Stay ahead of the queue</h3><p className="muted">Review pending claims, attach receipts, and close each month with confidence.</p><div className="check-line"><Check /> API-connected workspace</div><div className="check-line"><Check /> Secure cookie sessions</div></section></div></> }
function Expenses({ rows, busy, query, setQuery, portal, onRefresh }) { return <section className="panel table-panel"><div className="panel-heading"><div><span className="kicker">{portal === 'admin' ? 'REVIEW QUEUE' : 'CLAIMS LEDGER'}</span><h3>{portal === 'admin' ? 'Claims needing attention' : 'Expense history'}</h3></div><div className="search-box"><Search /><input placeholder="Search expenses" value={query} onChange={e => setQuery(e.target.value)} /></div></div><div className="table-wrap"><table><thead><tr><th>Expense</th><th>Category</th><th>Amount</th><th>Status</th><th>Date</th>{portal === 'admin' && <th>Action</th>}</tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.title || row.description || 'Expense claim'}</strong><small>#{row.id}</small></td><td>{row.category_name || row.category || '—'}</td><td><b>{money(row.amount)}</b></td><td><span className={`status ${String(row.status || 'Pending').toLowerCase()}`}>{row.status || 'Pending'}</span></td><td>{row.expense_date || '—'}</td>{portal === 'admin' && <td><div className="row-actions"><button onClick={() => api(`/admin/expenses/${row.id}/status`, { method: 'PUT', body: { status: 'Approved', approved_by: 1 } }).then(onRefresh)}>Approve</button><button onClick={() => api(`/admin/expenses/${row.id}/status`, { method: 'PUT', body: { status: 'Rejected', approved_by: 1, remarks: 'Rejected from review queue' } }).then(onRefresh)}>Reject</button></div></td>}</tr>)}</tbody></table>{busy && <Empty text="Loading current claims…" />}{!busy && !rows.length && <Empty text="No expenses match this view." />}</div></section> }
function Reports({ portal }) { const [rows, setRows] = useState([]); useEffect(() => { api(portal === 'admin' ? '/admin/reports/payments?report_type=method' : portal === 'vendor' ? '/sub-vendor/reports/payments' : '/reports/by-category').then(setRows).catch(() => {}) }, [portal]); return <section className="panel"><div className="panel-heading"><div><span className="kicker">ANALYTICS</span><h3>Spend by category</h3></div><BarChart3 /></div>{rows.length ? rows.map((row, i) => <div className="bar-row" key={i}><span>{row.category_name || row.category || row.payment_method || 'Category'}</span><div className="bar-track"><i style={{ width: `${Math.min(100, Number(row.total || row.amount || 0) / Math.max(...rows.map(item => Number(item.total || item.amount || 1))) * 100)}%` }} /></div><b>{money(row.total || row.amount)}</b></div>) : <Empty text="Reports will appear when expenses are available." />}</section> }
function Wallet({ portal, data }) { const [wallet, setWallet] = useState(null); useEffect(() => { if (portal === 'vendor') api('/sub-vendor/wallet').then(setWallet).catch(() => {}); else if (data?.wallet) setWallet(data) }, [portal, data]); const balance = wallet?.wallet?.balance ?? wallet?.balance ?? data?.wallet_balance; return <div className="wallet-grid"><section className="balance-card"><span className="kicker">AVAILABLE BALANCE</span><strong>{money(balance)}</strong><p>Current wallet balance</p></section><section className="panel"><span className="kicker">TRANSACTIONS</span><h3>Wallet activity</h3>{(wallet?.transactions || []).map((tx, i) => <div className="activity-row" key={tx.id || i}><span className="avatar">₹</span><div><strong>{tx.description || tx.transaction_type}</strong><small>{tx.created_at || 'Recent'}</small></div><b>{money(tx.amount)}</b></div>)}{!wallet?.transactions?.length && <Empty text="No wallet transactions." />}</section></div> }
function Employees() { return <section className="panel empty-panel"><Users /><h3>Employee directory</h3><p className="muted">Create and manage employees through the sub-vendor API.</p><button className="primary-button" onClick={() => alert('Use the employee creation form from the API-connected workspace.')}>Add employee</button></section> }
function Categories() { return <section className="panel empty-panel"><Tags /><h3>Category library</h3><p className="muted">Manage categories, subcategories, and payment methods from the admin console.</p></section> }
function Vendors() { return <section className="panel empty-panel"><Users /><h3>Sub-vendor directory</h3><p className="muted">Review vendor accounts and account status from the connected API.</p></section> }
function ExpenseModal({ options, onClose, onSaved }) { const [form, setForm] = useState({ expense_date: new Date().toISOString().slice(0, 10), title: '', description: '', amount: '', category_id: '', subcategory_id: '', payment_method: '', created_by: '', remarks: '' }); const [saving, setSaving] = useState(false); const submit = async e => { e.preventDefault(); setSaving(true); const body = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value) body.append(key, value) }); try { await api(config.expense + (portal === 'employee' ? '/' : ''), { method: 'POST', body }); onSaved() } catch (err) { alert(err.message) } finally { setSaving(false) } }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="panel-heading"><div><span className="kicker">NEW CLAIM</span><h3>Add expense</h3></div><button type="button" className="icon-button" onClick={onClose}><X /></button></div><div className="form-grid"><label>Title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Amount<input required min="1" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /></label><label>Date<input required type="date" value={form.expense_date} onChange={e => setForm({ ...form, expense_date: e.target.value })} /></label><label>Category<select required value={form.category_id} onChange={e => setForm({ ...form, category_id: e.target.value })}><option value="">Select category</option>{(options?.categories || []).map(item => <option key={item.id} value={item.id}>{item.category_name || item.name}</option>)}</select></label><label>Payment method<select required value={form.payment_method} onChange={e => setForm({ ...form, payment_method: e.target.value })}><option value="">Select method</option>{(options?.payment_methods || []).map(item => <option key={item.id} value={item.name || item.payment_method}>{item.name || item.payment_method}</option>)}</select></label><label className="wide">Description<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label></div><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : 'Submit expense'}</button></div></form></div> }
function Empty({ text }) { return <div className="empty"><CircleDollarSign />{text}</div> }
createRoot(document.getElementById('root')).render(<App />)
