import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { LayoutDashboard, ReceiptText, BarChart3, WalletCards, Users, Tags, Bell, LogOut, Plus, RefreshCw, Check, X, Search, Menu } from 'lucide-react'
import './styles.css'

const portal = location.pathname.startsWith('/admin-ui') ? 'admin' : location.pathname.startsWith('/vendor-ui') ? 'vendor' : 'employee'
const cfg = { employee:{name:'Employee workspace', home:'Dashboard', nav:[['dashboard','Dashboard',LayoutDashboard],['expenses','Expenses',ReceiptText],['reports','Reports',BarChart3],['wallet','Wallet',WalletCards]]}, admin:{name:'Admin console',home:'Overview',nav:[['dashboard','Overview',LayoutDashboard],['pending','Pending approvals',ReceiptText],['reports','Reports',BarChart3],['wallet','Wallet',WalletCards],['categories','Categories',Tags],['vendors','Sub-vendors',Users]]}, vendor:{name:'Vendor workspace',home:'Dashboard',nav:[['dashboard','Dashboard',LayoutDashboard],['expenses','Expenses',ReceiptText],['employees','Employees',Users],['reports','Reports',BarChart3],['wallet','Wallet',WalletCards]]} }[portal]
const money = n => `₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
async function api(path, options={}) { const res=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options,body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body}); if(!res.ok){let d=res.statusText;try{d=(await res.json()).detail||d}catch{} throw Error(d)} return res.status===204?null:res.json() }

function App(){ const [view,setView]=useState('dashboard'); const [data,setData]=useState(null); const [busy,setBusy]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [showForm,setShowForm]=useState(false); const [mobile,setMobile]=useState(false)
 const load=async()=>{setBusy(true);setError('');try{const endpoint=portal==='admin'?'/admin/dashboard':portal==='vendor'?'/sub-vendor/dashboard':'/dashboard';setData(await api(endpoint))}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const rows=useMemo(()=>data?.expenses||data?.recent_expenses||data?.recent||[],[data]); const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))
 return <div className="shell"><aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><span className="mark">L</span><span>Ledger</span></div><div className="workspace">{cfg.name}<small>Expense operations</small></div><nav>{cfg.nav.map(([id,label,Icon])=><button className={view===id?'nav active':'nav'} onClick={()=>{setView(id);setMobile(false)}} key={id}><Icon size={17}/>{label}</button>)}</nav><div className="side-foot"><button className="nav"><Bell size={17}/>Notifications</button><button className="nav" onClick={()=>api(portal==='admin'?'/admin/logout':portal==='vendor'?'/sub-vendor/logout':'/logout').then(()=>location.reload())}><LogOut size={17}/>Sign out</button></div></aside>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<main><header><button className="icon-btn mobile-menu" onClick={()=>setMobile(true)}><Menu size={20}/></button><div><p className="eyebrow">{portal.toUpperCase()} / LEDGER</p><h1>{cfg.nav.find(x=>x[0]===view)?.[1]||cfg.home}</h1></div><div className="header-actions"><button className="icon-btn" onClick={load} aria-label="Refresh"><RefreshCw size={17}/></button>{(portal==='employee'||portal==='vendor')&&<button className="primary" onClick={()=>setShowForm(true)}><Plus size={17}/>New expense</button>}</div></header><section className="content">{error&&<div className="alert"><X size={17}/>{error}<button onClick={load}>Retry</button></div>}{view==='dashboard'&&<Dashboard data={data} portal={portal} busy={busy}/>} {view==='expenses'||view==='pending'?<ExpenseView rows={filtered} query={query} setQuery={setQuery} portal={portal} busy={busy}/>:null}{view==='reports'&&<Reports data={data} busy={busy}/>} {view==='wallet'&&<Wallet data={data} busy={busy}/>} {view==='categories'&&<Simple title="Category library" icon={Tags}/>} {view==='vendors'&&<Simple title="Sub-vendor directory" icon={Users}/>} {view==='employees'&&<Simple title="Employee directory" icon={Users}/>}</section></main>{showForm&&<ExpenseForm onClose={()=>setShowForm(false)} onSaved={()=>{setShowForm(false);load()}}/>}</div> }
function Dashboard({data,portal,busy}){const stats=portal==='admin'?[['Total spend',data?.total_amount],['All claims',data?.total_expenses],['Pending review',data?.pending],['Approved',data?.approved]]:[['Total spend',data?.total_amount],['Total claims',data?.total_expenses],['Pending',data?.pending],['Paid',data?.paid]];return <><div className="welcome"><div><p className="eyebrow">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</p><h2>Good morning, keep every rupee accountable.</h2><p className="muted">A clear view of your expense operations, updated from the Python API.</p></div><div className="pulse">LIVE <span/></div></div><div className="stats">{stats.map(([l,v])=><article className="stat" key={l}><span>{l}</span><strong>{busy?'—':l.includes('spend')?money(v):v??0}</strong><small>From current records</small></article>)}</div><div className="grid-2"><section className="panel"><div className="panel-head"><div><p className="eyebrow">ACTIVITY</p><h3>Recent expense activity</h3></div><ReceiptText size={18}/></div>{(data?.recent_expenses||data?.expenses||[]).slice(0,5).map((r,i)=><div className="row" key={r.id||i}><div className="avatar">{String(r.description||'E')[0]}</div><div><strong>{r.description||r.category||'Expense claim'}</strong><small>{r.category||'General'} · {r.status||'Pending'}</small></div><b>{money(r.amount)}</b></div>)}{!busy&&!data?.recent_expenses&&!data?.expenses&&<Empty/>}</section><section className="panel insight"><p className="eyebrow">OPERATIONS NOTE</p><h3>Stay ahead of the queue</h3><p className="muted">Review pending claims, keep receipts attached, and close the month with confidence.</p><div className="check"><Check size={16}/> API-connected workspace</div><div className="check"><Check size={16}/> Same-origin secure sessions</div></section></div></>}
function ExpenseView({rows,query,setQuery,portal,busy}){return <section className="panel table-panel"><div className="panel-head"><div><p className="eyebrow">{portal==='admin'?'REVIEW QUEUE':'CLAIMS LEDGER'}</p><h3>{portal==='admin'?'Claims needing attention':'Your expenses'}</h3></div><div className="search"><Search size={16}/><input placeholder="Search expenses" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="table-wrap"><table><thead><tr><th>Description</th><th>Category</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td><strong>{r.description||'Expense claim'}</strong><small>#{r.id||'—'}</small></td><td>{r.category||r.category_name||'—'}</td><td><b>{money(r.amount)}</b></td><td><span className={'badge '+String(r.status||'Pending').toLowerCase()}>{r.status||'Pending'}</span></td><td>{r.expense_date||r.created_at||'—'}</td></tr>)}</tbody></table>{busy&&<Empty text="Loading current claims…"/>}{!busy&&!rows.length&&<Empty text="No expenses match this view."/>}</div></section>}
function Reports({data,busy}){return <section className="panel"><div className="panel-head"><div><p className="eyebrow">ANALYTICS</p><h3>Spend by category</h3></div><BarChart3 size={18}/></div><div className="bars">{(data?.category_totals||data?.report||[]).map((r,i)=><div className="bar-row" key={i}><span>{r.category||r.name||'Category'}</span><div><i style={{width:`${Math.min(100,Number(r.total||r.amount||0)/Math.max(1,Number(data?.total_amount||1000))*100)}%`}}/></div><b>{money(r.total||r.amount)}</b></div>)}{!busy&&!data?.category_totals&&!data?.report&&<Empty text="Reports will appear once expenses are available."/>}</div></section>}
function Wallet({data,busy}){return <section className="wallet-grid"><div className="balance"><p className="eyebrow">AVAILABLE BALANCE</p><strong>{busy?'—':money(data?.wallet_balance||data?.balance)}</strong><p>Current wallet balance</p></div><section className="panel"><p className="eyebrow">TRANSACTIONS</p><h3>Wallet activity</h3><Empty text="No recent wallet transactions."/></section></section>}
function Simple({title,icon:Icon}){return <section className="panel empty-panel"><Icon size={28}/><h3>{title}</h3><p className="muted">Manage this workspace from the connected FastAPI service. Data will appear here as records are added.</p></section>}
function Empty({text='No recent activity.'}){return <div className="empty">{text}</div>}
function ExpenseForm({onClose,onSaved}){const [form,setForm]=useState({description:'',amount:'',category:'',expense_date:new Date().toISOString().slice(0,10)});const [saving,setSaving]=useState(false);const submit=async e=>{e.preventDefault();setSaving(true);try{await api('/expenses',{method:'POST',body:{...form,amount:Number(form.amount)}});onSaved()}catch(err){alert(err.message)}finally{setSaving(false)}};return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="panel-head"><div><p className="eyebrow">NEW CLAIM</p><h3>Add expense</h3></div><button type="button" className="icon-btn" onClick={onClose}><X size={18}/></button></div><label>Description<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Amount<input required min="1" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Expense date<input type="date" value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save expense'}</button></div></form></div>}
createRoot(document.getElementById('root')).render(<App/>)
